### ISSUE TITLE
Use `chezmoi` instead of `rsync` in diff and update scripts

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [aureooms/dotfiles#17]
Covers #3.

`chezmoi` cannot be used alone to handle multiple sources automatically (see https://github.com/twpayne/chezmoi/issues/189, https://github.com/twpayne/chezmoi/issues/226).
This will not be fixed.
Use `chezmoi` to handle syncing and diffing. We get templating for freezies.
Update the plugin mechanism to use `chezmoi` or `git` by default (autodetect or maybe move everything to use `chezmoi`).

**Comment by twpayne** [comment]
Author of chezmoi here. Just found this issue. Would you mind weighing in on https://github.com/twpayne/chezmoi/issues/753?

**Comment by make-github-pseudonymous-again** [comment]
@twpayne The way it is setup right now, chezmoi works for me. I do agree having to handle multiple sources is complex. I think chezmoi already solves enough issues. The file structure is nice and explicit.

**Comment by twpayne** [comment]
Thank you for the feedback :)
